const crewChoices = {

  recruit: {
    name: "",
    type: "Recruit",
    move: 6,
    fight: 2,
    shoot: 2,
    armor: 10,
    will: 0,
    health: 12,
    cost: 0,
    gear: ["Pistol", "Light Armor", "Knife"],
    soldierType: "standard",
  },

  runner: {
    name: "",
    type: "Runner",
    move: 7,
    fight: 2,
    shoot: 1,
    armor: 9,
    will: 1,
    health: 12,
    cost: 0,
    gear: ["Pistol", "Knife"],
    soldierType: "standard",
  },

  hacker: {
    name: "",
    type: "Hacker",
    move: 6,
    fight: 1,
    shoot: 1,
    armor: 10,
    will: 1,
    health: 12,
    cost: 20,
    gear: ["Pistol", "Deck", "Light Armor", "Knife"],
    soldierType: "standard",
  },

  chiseler: {
    name: "",
    type: "Chiseler",
    move: 6,
    fight: 1,
    shoot: 1,
    armor: 10,
    will: 1,
    health: 12,
    cost: 20,
    gear: ["Pistol", "Picks", "Light Armor", "Knife"],
  },

  guardDog: {
    name: "",
    type: "Guard Dog",
    move: 8,
    fight: 1,
    shoot: 0,
    armor: 8,
    will: -2,
    health: 10,
    cost: 10,
    note: ["Animal"],
  },

  sentry: {
    name: "",
    type: "Sentry",
    move: 5,
    fight: 3,
    shoot: 2,
    armor: 11,
    will: 0,
    health: 14,
    cost: 50,
    gear: ["Carbine", "Heavy Armor", "Hand Weapon"],
  },

  trooper: {
    name: "",
    type: "Trooper",
    move: 5,
    fight: 2,
    shoot: 3,
    armor: 11,
    will: 0,
    health: 14,
    cost: 50,
    gear: ["Carbine", "Heavy Armor", "Knife"],
    soldierType: "standard",
  },

  medic: {
    name: "",
    type: "Medic",
    move: 7,
    fight: 2,
    shoot: 2,
    armor: 10,
    will: 3,
    health: 14,
    cost: 100,
    gear: ["Pistol", "Light Armor", "Medic Kit"],
    soldierType: "standard",
  },

  codebreaker: {
    name: "",
    type: "Codebreaker",
    move: 6,
    fight: 3,
    shoot: 2,
    armor: 10,
    will: 2,
    health: 14,
    cost: 75,
    gear: ["Carbine", "Deck", "Light Armor", "Knife"],
    soldierType: "specialist",
  },

  casecracker: {
    name: "",
    type: "Casecracker",
    move: 6,
    fight: 3,
    shoot: 2,
    armor: 10,
    will: 2,
    health: 14,
    cost: 75,
    gear: ["Carbine", "Picks", "Light Armor", "Knife"],
    soldierType: "specialist",
  },

  commando: {
    name: "",
    type: "Commando",
    move: 5,
    fight: 3,
    shoot: 3,
    armor: 11,
    will: 1,
    health: 14,
    cost: 75,
    gear: ["Carbine", "Grenades", "Heavy Armor", "Hand Weapon"],
    soldierType: "specialist",
  },

  pathfinder: {
    name: "",
    type: "Pathfinder",
    move: 7,
    fight: 3,
    shoot: 3,
    armor: 10,
    will: 2,
    health: 14,
    cost: 100,
    gear: ["Carbine", "Grenades", "Light Armor", "Hand Weapon"],
    soldierType: "specialist",
  },

  sniper: {
    name: "",
    type: "Sniper",
    move: 6,
    fight: 3,
    shoot: 4,
    armor: 10,
    will: 3,
    health: 14,
    cost: 100,
    gear: ["Carbine", "Light Armor", "Hand Weapon"],
    soldierType: "specialist",
  },

  grenadier: {
    name: "",
    type: "Grenadier",
    move: 5,
    fight: 3,
    shoot: 3,
    armor: 11,
    will: 2,
    health: 14,
    cost: 100,
    gear: ["Grenade Launcher", "Pistol", "Heavy Armor", "Knife"],
    soldierType: "specialist",
  },

  burner: {
    name: "",
    type: "Burner",
    move: 5,
    fight: 3,
    shoot: 2,
    armor: 11,
    will: 1,
    health: 14,
    cost: 100,
    gear: ["Flamethrower", "Pistol", "Heavy Armor", "Knife"],
    soldierType: "specialist",
  },

  gunner: {
    Name: "",
    type: "Gunner",
    move: 5,
    fight: 3,
    shoot: 3,
    armor: 11,
    will: 1,
    health: 14,
    cost: 100,
    gear: ["Rapid-fire", "Pistol", "Heavy Armor", "Knife"],
    soldierType: "specialist",
  },

  armoredTrooper: {
    name: "",
    type: "Armored Trooper",
    move: 6,
    fight: 4,
    shoot: 4,
    armor: 13,
    will: 3,
    health: 14,
    cost: 150,
    gear: ["Carbine", "Combat Armor"],
    soldierType: "specialist",
  },
};

